In [2]:
import numpy as np

In [3]:
arr = np.array([5,3,9,8,0,4])
arr

array([5, 3, 9, 8, 0, 4])

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr.ndim

1

In [6]:
arr.size

6

In [7]:
arr.shape

(6,)

In [8]:
arr_new = arr.reshape((1,6))

In [9]:
arr_new.ndim

2

In [12]:
arr_col = arr_new.reshape(6,1)
arr_col

array([[5],
       [3],
       [9],
       [8],
       [0],
       [4]])

In [13]:
arr_new+10

array([[15, 13, 19, 18, 10, 14]])

In [14]:
arr_new**2

array([[25,  9, 81, 64,  0, 16]])

In [15]:
arr_new**2

array([[25,  9, 81, 64,  0, 16]])

In [16]:
arr_num[arr_num % 2]

NameError: name 'arr_num' is not defined

In [17]:
arr_new[arr_new % 2]


IndexError: index 1 is out of bounds for axis 0 with size 1

In [18]:
arr_new[arr_new % 2 == 0]


array([8, 0, 4])

In [19]:
arr_new.mean()

4.833333333333333

In [20]:
mat = np.arange(1,16).reshape(3,5)

In [21]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [22]:
mat.mean(:,1)

SyntaxError: invalid syntax (2433486968.py, line 1)

In [23]:
mat.sum()

120

In [24]:
mat.sum(axis=1)

array([15, 40, 65])

In [25]:
mat.sum(axis=0)

array([18, 21, 24, 27, 30])

In [2]:
import numpy as np
a = np.array([[16, 5], [81, 6], [33, 1]])
x=np.transpose(a).reshape(2,3)
x 

array([[16, 81, 33],
       [ 5,  6,  1]])

In [5]:
import numpy as np
x = np.ones((5,5))
x


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [4]:
x[1:-1,1:-1] = 0
x


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
import numpy as np
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[1], [2]])
np.dot(arr1, arr2)

array([[ 5],
       [11]])

In [8]:
import numpy as np
A = np.arange(9).reshape(3,3)
print(A[:, ::-1])

[[2 1 0]
 [5 4 3]
 [8 7 6]]
